openapi: 3.0.3
info:
  title: Модели запросов и ответов эндпоинта some-endpoint
  version: 1.0.0
paths:
  /save-item:
    post:
      tags:
        - Item
      operationId: saveItem
      requestBody:
        $ref: '#/components/requestBodies/SaveItemRequest'
      responses:
        '200':
          description: Тело ответа на запрос на добавление товара на склад
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveItemResponse'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
      summary: Добавление нового товара на склад
components:
  requestBodies:
    SaveItemRequest:
      description: Тело запроса на добавление товара на склад
      required: true
      content:
        application/json:
          schema:
            required:
              - name
              - price
              - count
            type: object
            properties:
              name:
                $ref: '#/components/schemas/name'
              price:
                $ref: '#/components/schemas/price'
              count:
                $ref: '#/components/schemas/count'
  schemas:
    SaveItemResponse:
      required:
        - id
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
    id:
      description: Имя кондитерского изделия
      type: string
      format: uuid
      nullable: false
    name:
      description: Имя кондитерского изделия
      type: string
      example: "Холодильник"
      nullable: false
    price:
      description: Цена кондитерского изделия
      type: number
      example: 50_000
      nullable: false
    count:
      description: Количество доступного товара
      type: integer
      example: 5
      nullable: false