openapi: 3.0.3
info:
  title: Модели запросов и ответов эндпоинта some-endpoint
  version: 1.0.0
paths:
  /save-item:
    post:
      tags:
        - Item
      operationId: saveItem
      requestBody:
        $ref: '#/components/requestBodies/SaveItemRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '500':
          description: Internal server error
      summary: Добавление нового товара на склад
components:
  requestBodies:
    SaveItemRequest:
      description: Тело запроса на выполнение какой-то логики
      required: true
      content:
        application/json:
          schema:
            required:
              - name
              - price
            type: object
            properties:
              name:
                $ref: '#/components/schemas/name'
              price:
                $ref: '#/components/schemas/price'
              count:
                $ref: '#/components/schemas/count'
  schemas:
    name:
      description: Имя кондитерского изделия
      type: string
      example: "Холодильник"
    price:
      description: Цена кондитерского изделия
      type: number
      example: 50_000
    count:
      description: Количество доступного товара
      type: integer
      example: 5