version: '3.8'
services:
  store-warehouse-api-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - store-warehouse-api-database
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-warehouse-api-database/store-warehouse

  store-warehouse-api-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./resources/liquibase/changelog-master.yaml
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:

