spring:
  application:
    name: store-warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/bakery
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase/changelog-master.yaml

server:
  port:
    8080