spring:
  application:
    name: store-warehouse
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/store-warehouse}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase/changelog-master.yaml

server:
  port:
    ${SERVER_PORT:8080}