openapi: 3.0.3
info:
  title: API склада магазина
  version: 1.0.0
servers:
  - url: https://localhost:8080
tags:
  - name: Item
    description: Всё, связанное с товарами на складе
paths:
  /api/v1/item:
    $ref: 'resource/save-item.yaml#/paths/~1save-item'
  /api/v1/item/{id}:
    $ref: 'resource/get-item.yaml#/paths/~1get-item'
